spring:
  datasource:
    url: ${DB_URL}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    username: photoarchapp@gmail.com
    password: photo123!
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true


management:
  endpoint:
    mappings:
      enabled: true


  endpoints:
    web:
      exposure:
        include: mappings




