spring:
  datasource:
    url: jdbc:mysql://localhost/photoarchive?serverTimezone=Europe/Warsaw
    username: user1
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    username: photoarchiveapp@gmail.com
    password: photo123!
    port: 587
    properties: 
      mail.smpt.auth: true
      mail.smpt.starttls.enable: true
      mail.smpt.starttls.required: true
      mail.smpt.ssl.trust: smtp.gmail.com


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true


management:
  endpoint:
    mappings:
      enabled: true


  endpoints:
    web:
      exposure:
        include: mappings


